// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module Hello(	// \\src\\main\\scala\\Hello.scala:11:7
  input         clock,	// \\src\\main\\scala\\Hello.scala:11:7
                reset,	// \\src\\main\\scala\\Hello.scala:11:7
  input  [7:0]  io_din,	// \\src\\main\\scala\\Hello.scala:12:14
  output [15:0] io_dout,	// \\src\\main\\scala\\Hello.scala:12:14
  input         io_clear,	// \\src\\main\\scala\\Hello.scala:12:14
                io_enable	// \\src\\main\\scala\\Hello.scala:12:14
);

  reg [15:0] accReg;	// \\src\\main\\scala\\Hello.scala:19:23
  always @(posedge clock) begin	// \\src\\main\\scala\\Hello.scala:11:7
    if (reset)	// \\src\\main\\scala\\Hello.scala:11:7
      accReg <= 16'h0;	// \\src\\main\\scala\\Hello.scala:19:23
    else if (io_clear)	// \\src\\main\\scala\\Hello.scala:12:14
      accReg <= 16'h0;	// \\src\\main\\scala\\Hello.scala:19:23
    else if (io_enable)	// \\src\\main\\scala\\Hello.scala:12:14
      accReg <= accReg + {8'h0, io_din};	// \\src\\main\\scala\\Hello.scala:19:23, :24:22
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// \\src\\main\\scala\\Hello.scala:11:7
    `ifdef FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\Hello.scala:11:7
      `FIRRTL_BEFORE_INITIAL	// \\src\\main\\scala\\Hello.scala:11:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// \\src\\main\\scala\\Hello.scala:11:7
      automatic logic [31:0] _RANDOM[0:0];	// \\src\\main\\scala\\Hello.scala:11:7
      `ifdef INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\Hello.scala:11:7
        `INIT_RANDOM_PROLOG_	// \\src\\main\\scala\\Hello.scala:11:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// \\src\\main\\scala\\Hello.scala:11:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// \\src\\main\\scala\\Hello.scala:11:7
        accReg = _RANDOM[/*Zero width*/ 1'b0][15:0];	// \\src\\main\\scala\\Hello.scala:11:7, :19:23
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\Hello.scala:11:7
      `FIRRTL_AFTER_INITIAL	// \\src\\main\\scala\\Hello.scala:11:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_dout = accReg;	// \\src\\main\\scala\\Hello.scala:11:7, :19:23
endmodule

